/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:8b2718d1-e806-495f-9f82-fdd8c07ff38b",
    "aws_cognito_region": "eu-west-2",
    "oauth": {},
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "ZCTbot",
            "alias": "PandemicBot",
            "region": "eu-west-2"
        }
    ]
};

export default awsmobile;
