version: '3'
services:
    client:
        container_name: client
        restart: always
        build: ./client
        ports:
            - '3000:3000'
    api:
        container_name: mysql
        restart: always
        build: ./server 
        ports: 
            - '3001:3001'